Repository googleapis/python-security-private-ca, pull requests merged in 2021-04, with the labels that each got.

#31 chore: add license headers
  .pre-commit-config.yaml
  docs/conf.py
  security-privateca-v1beta1-py.tar.gz
  synth.metadata
Labels: api: security-privateca, cla: yes, context: partial

#29 chore: Migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .pre-commit-config.yaml
  docs/conf.py
  owlbot.py
  synth.metadata
Labels: api: security-privateca, automerge, cla: yes

#34 chore: prevent normalization of semver versioning
  setup.py
Labels: api: security-privateca, automerge, cla: yes

#40 chore(revert): revert preventing normalization
  setup.py
Labels: api: security-privateca, cla: yes
